export const AUTOMATION_MAIN_LOADING = "AUTOMATION_MAIN_LOADING";
export const AUTOMATION_MAIN_SUCCESS = "AUTOMATION_MAIN_SUCCESS";
export const AUTOMATION_MAIN_FAILED = "AUTOMATION_MAIN_FAILED";
export const AUTOMATION_MAIN_CLEAR = "AUTOMATION_MAIN_CLEAR";
export const DEBUGGER_LOADING = "DEBUGGER_LOADING";
export const DEBUGGER_SUCCESS = "DEBUGGER_SUCCESS";
export const DEBUGGER_FAILED = "DEBUGGER_FAILED";
export const DEBUGGER_CLEAR = "DEBUGGER_CLEAR";
